C_SHARP/BookingManagement/BookingManagement.Web/Models/ErrorViewModel.cs
namespace BookingManagement.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

C_SHARP/BookingManagement/BookingManagement.Web/Controllers/HomeController.cs
using BookingManagement.Web.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BookingManagement.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

C_SHARP/BookingManagement/BookingManagement.Web/Controllers/VillaController.cs
using BookingManagement.Domain.Entities;
using BookingManagement.Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace BookingManagement.Web.Controllers
{
    public class VillaController : Controller
    {
        private readonly ApplicationDbContext _dbContext;
        public VillaController(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task<IActionResult> Index()
        {
            var villas = await _dbContext.Villas.ToListAsync();
            return View(villas);
        }

        public async Task<IActionResult> Create()
        {
            return await Task.FromResult(View());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Villa obj)
        {
            if (!ModelState.IsValid)
                return View(obj);

            _dbContext.Villas.Add(obj);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction("Index");
        }
    }
}

C_SHARP/BookingManagement/BookingManagement.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

C_SHARP/BookingManagement/BookingManagement.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookingManagement.Web</title>
    @* Bootstrap 5.3.2 *@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/css/bootstrap.min.css" integrity="sha512-b2QcS5SsA8tZodcDtGRELiGv5SaKSk1vDHDaQRda0htPYWZ6046lr3kJ5bAAQdpV2mmA/4v0wQF9MyU6/pDIAg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @* Icon Bootstrap *@
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/BookingManagement.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookingManagement.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Villa" asp-action="Index">Villa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookingManagement.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* Bootstrap 5.3.2 *@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.min.js" integrity="sha512-WW8/jxkELe2CAiE4LvQfwm1rajOS8PHasCCx+knHG0gBHt8EXxS6T6tJRTGuDQVnluuAvMxWF4j8SNFDKceLFg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

C_SHARP/BookingManagement/BookingManagement.Web/Views/Villa/Create.cshtml
@{
    ViewData["Title"] = "Villa Create";
}

@model Villa


<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Create Villa</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <form method="post" class="row" enctype="multipart/form-data">
            <div class="p-3">
                <div class="form-floating py-1 col-12">
                    <input asp-for="Name" class="form-control border shadow" />
                    <label asp-for="Name" class="ms-2"></label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Description" class="form-control border shadow" />
                    <label asp-for="Description" class="ms-2"></label>
                    <span asp-validation-for="Description" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Price" class="form-control border shadow" />
                    <label asp-for="Price" class="ms-2"></label>
                    <span asp-validation-for="Price" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Sqft" class="form-control border shadow" />
                    <label asp-for="Sqft" class="ms-2"></label>
                    <span asp-validation-for="Sqft" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="Occupancy" class="form-control border shadow" />
                    <label asp-for="Occupancy" class="ms-2"></label>
                    <span asp-validation-for="Occupancy" class="text-danger"></span>
                </div>
                <div class="form-floating py-1 col-12">
                    <input asp-for="ImageUrl" class="form-control border shadow" />
                    <label asp-for="ImageUrl" class="ms-2 "></label>
                    <span asp-validation-for="ImageUrl" class="text-danger"></span>
                </div>
                <div class="row pt-2">
                    <div class="col-6 col-md-3">
                        <button type="submit" class="btn btn-success w-100">
                            <i class="bi bi-check-circle"></i> Create
                        </button>
                    </div>
                    <div class="col-6 col-md-3">
                        <a asp-controller="Villa" asp-action="Index" class="btn btn-secondary w-100">
                            <i class="bi bi-x-circle"></i> Cancel
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

C_SHARP/BookingManagement/BookingManagement.Web/Views/Villa/Index.cshtml
@{
    ViewData["Title"] = "Villa";
}

@model IEnumerable<Villa>

<div class="w-100 card border-0 p-4">
    <div class="card-header bg-success bg-gradient ml-0 py-3">
        <div class="row">
            <div class="col-12 text-center">
                <h2 class="text-white py-2">Villa List</h2>
            </div>
        </div>
    </div>
    <div class="card-body border p-4">
        <div class="row pb-3">
            <div class="col-6 offset-6 text-end">
                <a asp-controller="Villa" asp-action="Create" class="btn btn-secondary">
                    <i class="bi bi-plus-circle"></i> Create New Villa
                </a>
            </div>
        </div>

        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        Name
                    </th>
                    <th>Price</th>
                    <th>Sqft</th>
                    <th>Occupancy</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var obj in Model)
                {
                    <tr>
                        <td>@obj.Name</td>
                        <td>@obj.Price</td>
                        <td>@obj.Sqft</td>
                        <td>@obj.Occupancy</td>
                        <td>
                            <div class="w-75 btn-group" role="group">
                                <a asp-controller="Villa" asp-action="Update" asp-route-villaId="@obj.Id"
                                   class="btn btn-success mx-2">
                                    <i class="bi bi-pencil-square"></i> Edit
                                </a>
                                <a asp-controller="Villa" asp-action="Delete" asp-route-villaId="@obj.Id"
                                   class="btn btn-danger mx-2">
                                    <i class="bi bi-trash-fill"></i> Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>