C_SHARP/StudentManagement/StudentManagement.PresentationLayer.WebAppMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using StudentManagement.Shared.Entities;
using System.Diagnostics;

namespace StudentManagement.PresentationLayer.WebAppMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

C_SHARP/StudentManagement/StudentManagement.PresentationLayer.WebAppMVC/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Mvc;
using StudentManagement.DataAccessLayer.Database.Data;
using StudentManagement.Shared.Entities;

namespace StudentManagement.PresentationLayer.WebAppMVC.Controllers
{
    public class StudentsController : Controller
    {
        #region Private fields
        private readonly ApplicationDbContext _context;
        #endregion

        #region Constructor
        public StudentsController(ApplicationDbContext context)
        {
            _context = context;
        }
        #endregion

        #region Methods
        public IActionResult Index()
        {
            List<Student> students = _context.Students.ToList();
            return View(students);
        }

        public async Task<IActionResult> InsertUpdateAsync(Guid? id)
        {
            ///note: always pass student into View InsertUpdate 
            ///if Insert: student default created
            Student? student = new Student();
            if (id is null)
            {
                //create request
                return View(student);
            }
            //update request
            student = await _context.Students.FindAsync(id);
            if (student is null)
            {
                return NotFound();
            }
            return View(student);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> InsertUpdate(Student student)
        {
            ///if there are any modelstate validations on Student object => trigger validations
            if (ModelState.IsValid)
            {
                if (student.Id == new Guid())
                {
                    //create request
                    await _context.AddAsync(student);
                }
                else
                {
                    //update request
                    _context.Update(student);
                }
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(student);
        }


        public async Task<IActionResult> DeleteAsync(Guid id)
        {
            var student = _context.Students.Find(id);
            if (student is null)
            {
                return NotFound();
            }
            _context.Remove(student);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        #endregion
    }
}

C_SHARP/StudentManagement/StudentManagement.PresentationLayer.WebAppMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

C_SHARP/StudentManagement/StudentManagement.PresentationLayer.WebAppMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentManagement.PresentationLayer.WebAppMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentManagement.PresentationLayer.WebAppMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StudentManagement.PresentationLayer.WebAppMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - StudentManagement.PresentationLayer.WebAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

C_SHARP/StudentManagement/StudentManagement.PresentationLayer.WebAppMVC/Views/Students/Index.cshtml
@model IEnumerable<Student>

<br />
<br />
<div class="border p-4 bg-white">
    <div class="row">
        <div class="col-9">
            <h2 class="text-info"> Student List </h2>
        </div>

        <div class="col-3 text-right">
            <a asp-action="InsertUpdate" class="btn btn-info form-control"> Create New </a>
        </div>
    </div>
        @if (Model.Count() > 0)
        {
            <table class="table table-striped border">
                <tr class="table-secondary">
                    <th>
                        Student Name
                    </th>
                    <th></th>
                </tr>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @item.Name
                        </td>
                        <td>
                            <a class="btn btn-primary text-white" asp-action="InsertUpdate" asp-route-Id="@item.Id">
                                Edit
                            </a>

                            <a class="btn btn-danger text-white" asp-action="Delete" asp-route-Id="@item.Id">
                                Delete
                            </a>
                        </td>
                    </tr>
                }
            </table>
        }
        else
        {
            <p>No Student exists...</p>
        }
    </div>
</div>

C_SHARP/StudentManagement/StudentManagement.PresentationLayer.WebAppMVC/Views/Students/InsertUpdate.cshtml
@model Student
@{
    var action = (Model.Id != new Guid()) ? "Update" : "Create";
    var title = $"{action} Student";
}
<form method="post">
    <div class="row p-3 border">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="Id" />
        <div class="col-12 border-bottom">
            <h2 class="text-primary">@title</h2>
        </div>
        <div class="col-8 pt-4">
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="Code"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Code" class="form-control" />
                    <span asp-validation-for="Code" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="BirthDate"></label>
                </div>
                <div class="col-8">
                    <input asp-for="BirthDate" class="form-control" />
                    <span asp-validation-for="BirthDate" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="PhoneNumber"></label>
                </div>
                <div class="col-8">
                    <input asp-for="PhoneNumber" class="form-control" />
                    <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row py-2">
                <div class="col-4">
                    <label asp-for="Gender"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Gender" class="form-check-input" />
                    <span asp-validation-for="Gender" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group row">
                <div class="col-4 offset-4">
                    @if (Model.Id != new Guid())
                    {
                                        <button type="submit" class="btn btn-primary form-control">Update</button>
                    }
                    else
                    {
                                        <button type="submit" class="btn btn-primary form-control">Create</button>
                    }
                </div>
                <div class="col-4">
                    <a asp-action="Index" class="btn btn-success form-control">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
                    <partial name="_ValidationScriptsPartial" />
}